src/Entity/Security/RefreshToken.php
<?php

declare(strict_types=1);

namespace App\Entity\Security;

use App\Entity\Member;
use App\Repository\RefreshTokenRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=RefreshTokenRepository::class)
 */
class RefreshToken
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="uuid", unique=true)
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $expiresAt;

    /**
     * @ORM\ManyToOne(targetEntity=Member::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?UuidInterface
    {
        return $this->id;
    }

    /**
     * @param string|UuidInterface $id
     * @SuppressWarnings(PHPMD.StaticAccess)
     */
    public function setId($id): self
    {
        if (!$id instanceof UuidInterface) {
            $id = Uuid::fromString((string) $id);
        }

        $this->id = $id;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getExpiresAt(): ?\DateTimeInterface
    {
        return $this->expiresAt;
    }

    public function setExpiresAt(\DateTimeInterface $expiresAt): self
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }

    public function getUser(): ?UserInterface
    {
        return $this->user;
    }

    public function setUser(UserInterface $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function isExpired(): bool
    {
        return new DateTimeImmutable() > $this->expiresAt;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Security\AccountBannedException;
use App\Security\AccountDeniedLoginException;
use App\Security\AccountMailNotConfirmedException;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Exception\AccountExpiredException;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

/**
 * Controller used to manage the application security.
 */
class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="login", defaults={"access_denied_redirect" = "/"}))
     * @Route("/login", name="security_login", defaults={"access_denied_redirect" = "/"}))
     * @Route("/login_check", name="security_check", defaults={"access_denied_redirect" = "/"}))
     *
     * @return Response
     */
    public function loginAction(AuthenticationUtils $helper)
    {
        $user = $this->getUser();
        if (null !== $user) {
            return $this->redirectToRoute('homepage');
        }

        $error = $helper->getLastAuthenticationError();
        $lastUsername = $helper->getLastUsername();

        $showInvalidCredentialsHint = false;
        $showResendConfirmationLink = false;
        $showBannedHint = false;
        $showExpiredHint = false;
        $showNotAllowedToLogin = false;
        if (\is_object($error)) {
            switch (\get_class($error)) {
                case AccountMailNotConfirmedException::class:
                    $showResendConfirmationLink = ($lastUsername) ? true : false;
                    break;
                case BadCredentialsException::class:
                    $showInvalidCredentialsHint = true;
                    break;
                case AccountBannedException::class:
                    $showBannedHint = true;
                    break;
                case AccountDeniedLoginException::class:
                    $showNotAllowedToLogin = true;
                    break;
                case AccountExpiredException::class:
                    $showExpiredHint = true;
                    break;
                default:
                    ;
            }
        }

        $content = $this->render(
            'security/login.html.twig',
            [
                'last_username' => $lastUsername,
                'error' => $error,
                'resend_confirmation' => $showResendConfirmationLink,
                'invalid_credentials' => $showInvalidCredentialsHint,
                'member_banned' => $showBannedHint,
                'member_expired' => $showExpiredHint,
                'member_not_allowed_to_login' => $showNotAllowedToLogin,
            ]
        );

        return $content;
    }

    /**
     * This is the route the user can use to logout.
     *
     * But, this will never be executed. Symfony will intercept this first
     * and handle the logout automatically. See logout in app/config/security.yml
     *
     * @Route("/logout", name="security_logout")
     *
     * @throws Exception
     */
    public function logoutAction()
    {
        throw new Exception('This should never be reached!');
    }
}

templates/security/access.denied.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <h1>{{ 'access.denied' }}</h1>
    <p>{{ message | trans }}</p>
{% endblock content %}

templates/security/login.html.twig
{% import 'macros.twig' as macros %}
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="/">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ asset('favicon.ico') }}">
    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}"/>

    <title>
        {% apply spaceless %}
            {{ 'login' | trans }} | BeWelcome
        {% endapply %}
    </title>

    <meta name="description" content="{{ 'default_meta_description' | trans }}">
    <meta name="keywords" content="{{ 'default_meta_keyword' | trans }}">
    <meta name="robots" content="{{ 'robots' | trans }}">

    {% include 'webpreview.html.twig' %}

    {{ encore_entry_link_tags('bewelcome') }}
    <base id="baseuri" href="{{ app.request.schemeAndHttpHost ~ app.request.baseUrl }}">

    <link rel="manifest" href="{{ asset('manifest.webmanifest') }}">
    <script>
        // Check that service workers are supported
        if ('serviceWorker' in navigator) {
            // Use the window load event to keep the page load performant
            window.addEventListener('load', () => {
                navigator.serviceWorker.register('{{ asset('service-worker.js') }}');
            });
        }
    </script>
</head>
<body style="
  /* Location of the image */
  background-image: url(/images/homepicture-1200px_1-min.jpg);

  /* Background image is centered vertically and horizontally at all times */
  background-position: center center;

  /* Background image doesn't tile */
  background-repeat: no-repeat;

  /* Background image is fixed in the viewport so that it doesn't move when
     the content's height is greater than the image's height */
  background-attachment: fixed;

  /* This is what makes the background image rescale based
     on the container's size */
  background-size: cover;

  /* Set a background color that will be displayed
     while the background image is loading */
  background-color: #464646;
">
<nav class="navbar navbar-sticky-top navbar-expand-md navbar-dark bg-primary navbar-shadow bordert-1 borderb-1">
    <div class="container-lg">
        <a class="navbar-brand mr-3 float-left" href="{{ url('homepage') }}"><img
                    src="{{ asset('images/logo_index_top.png') }}" alt="BeWelcome"/></a>
    </div>
</nav>
{% block content %}
<main role="main">
    <noscript>
        <div class="container-lg">
            <div class="alert alert-danger"><p class="h5">You need to activate Javascript for bewelcome.org</p><small>Without
                    it some function won't work.</small></div>
        </div>
    </noscript>
    <div class="container-lg">
        {% for label, messages in app.flashes %}
            <div class="row">
                {% for message in messages %}
                    <div class="col-12">
                        <div class="alert alert-{{ label }}">
                            {{ message }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <div class="container-lg">
        <div class="row">
            <div class="col-10 offset-1 col-md-6 offset-md-3 col-sm-8 offset-sm-2 mb-3">
                {% for flash_message in app.session.flashBag.get('error') %}
                    <div class="flash error">
                        {{ flash_message | trans }}
                    </div>
                {% endfor %}
                {% for flash_message in app.session.flashBag.get('notice') %}
                    <div class="flash notice">
                        {{ flash_message | trans }}
                    </div>
                {% endfor %}
                <h1 class="text-center white">BeWelcome - {{ 'indexpageteaseropendoor' | trans }}</h1>
            </div>
            {% if error %}
                <div class="col-12">
                    <div class="alert alert-danger">
                        {{ error.messageKey|trans(error.messageData, 'security') }}
                    </div>
                </div>
            {% endif %}

            <div class="col-10 offset-1 col-sm-8 offset-sm-2">
                <div class="card-deck">
                    <div class="card">
                        <form id="main-login-form" role="form" method="post"
                              action="{{ path('security_check') }}">
                            <div class="card-body p-2">
                                <h4 class="card-title">{{ 'login' | trans }}</h4>
                                <div class="form-group">
                                    <label class="m-0" for="login-u">{{ 'username' | trans }}</label>
                                    <input type="text" id="login-u" name="_username" autofocus required
                                           value="{{ last_username }}"
                                           class="form-control">
                                </div>
                                <div class="form-group">
                                    <label class="m-0" for="login-p">{{ 'password' | trans }}</label>
                                    <input type="password" id="login-p" name="_password" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="login-r">
                                        <input type="checkbox" id="login-r" value="1"
                                               name="_remember_me">&nbsp;{{ 'stayloggedin' | trans }}
                                    </label>
                                </div>
                                <input type="hidden" name="_csrf_token"
                                       value="{{ csrf_token('authenticate') }}"
                                >
                                {% if invalid_credentials or resend_confirmation or member_banned or member_expired or member_not_allowed_to_login %}
                                    <p class="col-12 mt-3">
                                        {% if invalid_credentials %}
                                            {{ 'login.forgot.password' | trans }}<br>
                                            <a href="{{ url('member_request_reset_password') }}">{{ 'login.password.getnew' | trans }}</a>
                                            <br>
                                            {{ 'login.forgot.username' | trans }}
                                        {% endif %}
                                        {% if resend_confirmation %}
                                            {{ 'login.mail.not_confirmed' | trans }}<br>
                                            <a href="{{ url('resend_confirmation_email', { 'username': last_username}) }}">{{ 'login.resend.confirmation' | trans }}</a>
                                        {% endif %}
                                        {% if member_banned %}
                                            {{ 'login.account.banned' | trans }}
                                        {% endif %}
                                        {% if member_expired %}
                                            {{ 'login.account.expired' | trans }}
                                        {% endif %}
                                        {% if member_not_allowed_to_login %}
                                            {{ 'login.account.no_login' | trans }}
                                        {% endif %}
                                        <br>
                                        <a href="{{ url('feedback', { 'IdCategory': 3}) }}">{{ 'login.contact.support' | trans }}</a>
                                    </p>
                                {% endif %}
                            </div>
                            <div class="card-footer">
                                <button type="submit"
                                        class="btn btn-primary btn-block">{{ 'indexpageloginsubmit' | trans }}</button>
                            </div>
                        </form>
                    </div>
                    <div class="card">
                        <div class="card-body p-2">
                            <h4 class="card-title">{{ 'signupnow' | trans }}</h4>
                            <div class="form-group">
                                <label>{{ 'login.signup.info'|trans|raw }}</label>
                            </div>
                        </div>
                        <div class="card-footer"><a href="{{ url('signup_1') }}" class="btn btn-primary btn-block" role="button">
                                {{ 'signup'|trans }}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}
{% include 'footer.html.twig' %}
{{ encore_entry_script_tags('bewelcome') }}
<script type="application/javascript">
    $(".select2").select2({
        theme: 'bootstrap4',
        width: 'auto',
        dropdownAutoWidth: true
    });
</script>
</body>
</html>